arguments:
  format: json
git_services:
  - host: github.com
    repos:
      - redhat-appstudio/rhtap-cli
      - redhat-appstudio/tssc-sample-templates
      - redhat-appstudio/tssc-sample-pipelines
      - redhat-appstudio/tssc-sample-jenkins
      - redhat-appstudio/tssc-sample-gitops
      - redhat-appstudio/tssc-dev-gitops
      - redhat-appstudio/tssc-sample-sbom-scans
      - redhat-appstudio/tssc-dev-multi-ci
    token: "${GITHUB_TOKEN}"
    type: github
